# Generated by Django 2.0.9 on 2025-01-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_send', models.CharField(max_length=100)),
                ('message_reply', models.TextField(max_length=100)),
                ('message_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_date', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('reply_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=100)),
                ('image2', models.CharField(max_length=100)),
                ('image3', models.CharField(max_length=100)),
                ('image4', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('request_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('PORTFOLIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('review_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.login')),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.login')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='WORKER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.worker'),
        ),
        migrations.AddField(
            model_name='requests',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.user'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='WORKER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.worker'),
        ),
        migrations.AddField(
            model_name='payment',
            name='REQUEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.requests'),
        ),
        migrations.AddField(
            model_name='material',
            name='REQUEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.requests'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.login'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.user'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='WORKER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.worker'),
        ),
        migrations.AddField(
            model_name='chat',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='WORKER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.worker'),
        ),
        migrations.AddField(
            model_name='budget',
            name='REQUEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildconnect.requests'),
        ),
    ]
